branches:
  only:
    - master

language: php

php:
- 8.0
- 7.4
- 5.6

cache:
  directories:
    - $HOME/.cache/composer

before_install: composer validate --strict

install:
  - composer install
  - "[ $TRAVIS_PHP_VERSION != '8.0' ] || composer update phpunit/phpunit --ignore-platform-reqs --with-dependencies"

script:
  - php -l src/db.php || exit 1
  - composer test
